# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"werkzeug.cached_property": "rest.ipynb",
         "app": "rest.ipynb",
         "api": "rest.ipynb",
         "ns": "rest.ipynb",
         "scrum": "rest.ipynb",
         "ProjectList": "rest.ipynb",
         "project_model": "rest.ipynb",
         "Project": "rest.ipynb",
         "is_valid_store": "rest.ipynb",
         "invalid_store": "rest.ipynb",
         "StoryList": "rest.ipynb",
         "Story": "rest.ipynb",
         "story_model": "rest.ipynb",
         "Scrum": "services.ipynb"}

modules = ["rest.py",
           "services.py"]

doc_url = "https://TheGF.github.io/quick-scrum/"

git_url = "https://github.com/TheGF/quick-scrum/tree/master/"

def custom_doc_links(name): return None
